### PR TITLE
Adding podspec

### PR DESCRIPTION
**Pull request by levieggertcru**
Adding podspec to the shared RequestOperation Swift package in the event we need it for the shared MPDX-ios library.

### CODE REVIEW

**Review by gyasistory — CHANGES_REQUESTED** [review]
There will need to be a GitHub actions for both the swift packages and cocoapods.  

Swift Package would run `swift build`
Cocoapods would run  `pod lib lint
`

**Comment by frett** [comment]
I'm going to defer to @gyasistory on this PR since he's on top of things already :)

**Comment by levieggertcru** [comment]
Hey @gyasistory added those.  However, seems swift build can't recognize the RequestResponse public variables from an extension :(

**Comment by gyasistory** [comment]
> Hey @gyasistory added those. However, seems swift build can't recognize the RequestResponse public variables from an extension :( not much I can do about that.

@levieggertcru I would recommend doing a little research to see if you can resolve this issue.  I am sure someone has dealt with this before.  I think it is best to have ` swift build` or see if there is another swift command that you can run to check the code.

**Review by gyasistory — APPROVED** [review]

**Pull request merged**
